### ISSUE TITLE
Add 'babel-root-import' plugin to avoid long relative paths without local linking

### ISSUE THREAD

**Issue by namniak** [Jam3/generator-jam3#230]
This has not been tested yet in a project but looks legit and handy. @njam3 pls approve if good to go

**Comment by njam3** [comment]
@namniak Looking into maybe using https://www.npmjs.com/package/linklocal instead. Would like thoughts from everyone though. @Jam3/jam3-devs

**Comment by cheapsteak** [comment]
Dunno how much it matters, but it looks kind of like linklocal usage is dropping while babel-root-slash-import adoption is picking up

![image](https://cloud.githubusercontent.com/assets/743976/17524024/c2133714-5e2a-11e6-9e3a-dafc1c4a5921.png)

Shameless plug 🙂: 
http://npmcharts.com/compare/babel-root-slash-import,linklocal

**Comment by iranreyes** [comment]
Kudos @cheapsteak, really useful web app!!!!

In my opinion, going away from the charts, I like more the `linklocal` solution because it is more clear in the code and let you customize the names. 

I was playing around with `babel-root-import` and the link are with symbols. So if you want to setup for example a link for `component` you need to use `~, @` or other symbol. But doesn't resolve names. This not scale really well, because you need to check everytime what does the symbols mean

In the other case `linklocal`, you can set names like `components` that indeed is meanful

**Comment by namniak** [comment]
Note that either of these needs to be avoided when it comes to reusable components because UI generator won't be able to properly grab those local dependencies when post publishing the module.

**Comment by njam3** [comment]
Approved to setup `linklocal`

**Comment by njam3** [comment]
Closed as not really needed.
