### ISSUE TITLE
Connecting sections to store breaks transition groups

### ISSUE THREAD

**Issue by njam3** [Jam3/generator-jam3#275]

**Comment by BrendanNeufeld** [comment]
Need to decorate with `ConnectTransitionWrapper` https://gist.github.com/duro/0534a9c5fe4bd8b868a8
e.g. https://github.com/Jam3/prj-fb-messenger/blob/master/prj-frontend/src/sections/Landing/Landing.js

**Comment by BrendanNeufeld** [comment]
In the future any generated (redux) connect components that use `transition-group` will need this decorator.

**Comment by namniak** [comment]
We could bring in this module https://www.npmjs.com/package/connect-with-transition-group instead of having a local decorator.
But we don't have `connect` wrappers for sections or components  out of the box (I WISH WE DID https://github.com/Jam3/generator-jam3/issues/317) so nothing to update in terms of code.

**Comment by namniak** [comment]
https://github.com/Jam3/generator-jam3/pull/326
